//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZplrmApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZplrmDbEntities : DbContext
    {
        public ZplrmDbEntities()
            : base("name=ZplrmDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Doktori> Doktori { get; set; }
        public DbSet<Gradovi> Gradovi { get; set; }
        public DbSet<Prezenteri> Prezenteri { get; set; }
        public DbSet<Rabotilnici> Rabotilnici { get; set; }
        public DbSet<RabotilniciDoktori> RabotilniciDoktori { get; set; }
        public DbSet<RabotilniciPrezenteri> RabotilniciPrezenteri { get; set; }
        public DbSet<Temi> Temi { get; set; }
    }
}
