//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZplrmApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RabotilniciPrezenteri
    {
        public int RabotilnicaPrezenterId { get; set; }
        public int RabotilnicaId { get; set; }
        public string PrezenterFaksimil { get; set; }
    
        public virtual Prezenteri Prezenteri { get; set; }
        public virtual Rabotilnici Rabotilnici { get; set; }
    }
}
