//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZplrmApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rabotilnici
    {
        public Rabotilnici()
        {
            this.RabotilniciDoktori = new HashSet<RabotilniciDoktori>();
            this.RabotilniciPrezenteri = new HashSet<RabotilniciPrezenteri>();
        }
    
        public int RabotilnicaId { get; set; }
        public int TemaId { get; set; }
        public int GradId { get; set; }
        public string Mesto { get; set; }
        public string Lokacija { get; set; }
        public System.DateTime Datum { get; set; }
        public System.TimeSpan Pocetok { get; set; }
        public System.TimeSpan Kraj { get; set; }
        public Nullable<int> Bodovi { get; set; }
        public Nullable<int> OptimumPosetiteli { get; set; }
    
        public virtual Gradovi Gradovi { get; set; }
        public virtual Temi Temi { get; set; }
        public virtual ICollection<RabotilniciDoktori> RabotilniciDoktori { get; set; }
        public virtual ICollection<RabotilniciPrezenteri> RabotilniciPrezenteri { get; set; }
    }
}
