//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZplrmApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RabotilniciDoktori
    {
        public int RabotilnicaDoktorId { get; set; }
        public int RabotilnicaId { get; set; }
        public string DoktorFaksimil { get; set; }
        public double UplataIznos { get; set; }
        public Nullable<System.DateTime> UplataDatum { get; set; }
        public System.DateTime VremePrijava { get; set; }
        public bool Prisuten { get; set; }
    
        public virtual Doktori Doktori { get; set; }
        public virtual Rabotilnici Rabotilnici { get; set; }
    }
}
